publish_mode: editorial_workflow

backend:
  name: github
  repo: two-first-names/queer-spoonies
  branch: main
  base_url: https://decap-proxy.engiqueer.net

media_folder: assets

collections:
- name: page
  label: Page
  folder: pages
  create: true
  preview_path: pages/{{ slug }}
  fields:
  - label: Layout
    name: layout
    widget: hidden
    default: post
  - label: Title
    name: title
    widget: string
  - label: Content
    name: body
    widget: markdown